### PR TITLE
fix powershell gallery link

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by chipitsine** [comment]
Related: https://github.com/Azure-Devops-PowerShell-Module/AzDevOps/issues/34

**Comment by jeffpatton1971** [comment]
Hey @chipitsine just saw this, is the documentation not working or not downloading? I've been focused on work stuff and have not been back here in a few.

**Comment by jeffpatton1971** [comment]
SIGH...i just realized...this is embarassing

**Review by jeffpatton1971 — APPROVED** [review]

**Comment by chipitsine** [comment]
it's not embarassing.
module is good. I use it.

**Comment by jeffpatton1971** [comment]
Good to hear, I have a release sitting locally that I need to push up, just not gotten around to it yet, will be breaking as the cmdlet prefix changes, so FYI

**Pull request merged**
